version: '3.8'
services:
  youtube_api:
    image: ovozen-youtube_api
    container_name: youtube_api_ovozen
    build: ./youtube_api
    ports:
      - "8000:8000"
    secrets:
      - youtube-api-key
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka_ovozen
    container_name: kafka_ovozen
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafkaui_ovozen
    ports:
      - "9021:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_ovozen
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  spark:
    image: ovozen-spark_api
    container_name: spark_ovozen
    build: ./spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - youtube_api
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark_worker_ovozen
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark

  hadoop_namenode:
    image: apache/hadoop:3
    container_name: hadoop_namenode_ovozen
    hostname: namenode
    command: [ "hdfs", "namenode" ]
    ports:
      - "9870:9870"
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"

  hadoop_datanode:
      image: apache/hadoop:3
      container_name: hadoop_datanode_ovozen
      command: [ "hdfs", "datanode" ]
      env_file:
        - ./config
      depends_on:
        - hadoop_namenode

  hadoop_resourcemanager:
      image: apache/hadoop:3
      container_name: hadoop_resourcemanager_ovozen
      hostname: resourcemanager
      command: [ "yarn", "resourcemanager" ]
      ports:
        - "8088:8088"
      env_file:
        - ./config
      depends_on:
        - hadoop_namenode

  hadoop_nodemanager:
      image: apache/hadoop:3
      container_name: hadoop_nodemanager_ovozen
      command: [ "yarn", "nodemanager" ]
      env_file:
        - ./config
      depends_on:
        - hadoop_namenode
        - hadoop_resourcemanager

  plotly_dash:
    image: ovozen-dashboard
    container_name: plotydash_ovozen
    build: ./dashboard
    ports:
      - "8050:8050"
secrets:
  youtube-api-key:
    file: ./youtube_api/secret.txt